spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-waitmillis: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 1000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #建表策略，这里用update，即根据实体更新表结构
      ddl-auto: update
      #表中字段命名策略,这里要引入hibernate的核心包，不然这个命名策略会报错
      naming: 
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/